name: convert_webp
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # curlに必要なパッケージをインストール
      - name: install webp
        run: sudo apt install webp

      # リポジトリ内のファイルをwebpに変換する。
      # 後で使うのでteeで結果とファイルを出力している
      - name: run curl
        run: curl -sf https://raw.githubusercontent.com/shimajima-eiji/Settings_Environment/main/for_Mac/file2webp.sh | sh -s -- . | tee file2webp.log
        
      # webp変換した場合のみ処理する
      - name: Commit files
        run: |
          if [ $(tail -n 1 file2webp.log) -ne 0 ]
          then
            git config --global user.email "${{ secrets.EMAIL }}"
            git config --global user.name "shimajima-eiji"
            git add -A
            git commit -m "[Update]converted webp by Github Actions"
            git pull
            git push
          fi

      # teeで作ったログファイルは不要なので削除。内容が知りたいならgithubを参照
      - name: remove checkfile
        run: rm file2webp.log
        
